### ISSUE TITLE
running tests fails

### ISSUE THREAD

**Issue by harlantwood** [digitalbazaar/authorization.io#39]
OSX Sierra, Node v6.9.1

The server runs fine, but tests throw an error:

```
$ npm test
> authorization.io@0.4.0 test ~/code/authorization.io
> node authorization.dev.js test

~/code/authorization.io/node_modules/bedrock/lib/bedrock.js:115
      throw err;
      ^

TypeError: Cannot read property 'vars' of undefined
    at Object.<anonymous> (~/code/authorization.io/configs/test.js:39:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at ~/code/authorization.io/authorization.dev.js:18:3
    at iterate (~/code/authorization.io/node_modules/async-node-events/lib/async-node-events.js:40:27)
2016-11-26T00:04:41.638Z - critical: worker 88648 exited with code 1
npm ERR! Test failed.  See above for more details.
```

**Comment by dlongley** [comment]
No longer applicable.
